### ISSUE TITLE
What version of Opium and Opium_kernel did you use?

### ISSUE THREAD

**Issue by idkjs** [vyorkin/ocaml-todo#1]
I tried building this project but get an error that `Opium_kernal` is not a module. I cant seem to get it installed. 

Thanks for sharing!

**Comment by vyorkin** [comment]
Hi @idkjs ! Let me try to build it myself in a few minutes

**Comment by vyorkin** [comment]
Yes, you're right, I'm not sure about the exact version I used at that time (I don't remember 😅), but you may try 0.18.x or even 0.17.x

**Comment by idkjs** [comment]
Been trying them all. There is a sweet spot for opium and the other deps. Actually had it working the other day when i was studying it but forgot to run `opam lock`. Last version that `Opium_kernel` in it was 18 so that should work but then the `Headers.t` starts complaining so have to see where that is coming from. Saved it in my fork for now. Will get back to it. 
Thanks for the feedback.
